### ISSUE TITLE
レポジトリを井斉さんの個人githubアカウントに移す

### ISSUE THREAD

**Issue by mikeda** [atsu0131/kintai#4]
練習のためにやってみるといいかなというのを思いついたらissueにしておきますね！

とりあえずrista-incにレポジトリ作っちゃいましたが、設定いじったりとかCircleCI等の外部ツール連携とかやってみるのは個人アカウント上のほうがやりやすいと思うので、このレポジトリを井斉さんの個人アカウントに移行しちゃいましょう。

やったことないけど自分がtransferすればいいのかな。ちょっとやってみます。

**Comment by mikeda** [comment]
@atsu0131 
直接owner移行できなかったのでこういう感じで進めました。

- publicにする
- mikedaの個人アカウントにtransfer
- atsu0131の個人アカウントにtransfer依頼

『Repository transfer to atsu0131 requested』というメッセージが出てるので、井斉さんにリクエストがメールかなんかで飛んでるのかな。
承認お願いします。

完了したら手元のレポジトリのremote urlをhttps://github.com/rista-inc/kintai から https://github.com/atsu0131/kintai に変更して下さい。

このコマンドを実行すれば良いのかな。

```
git remote set-url origin git@github.com:atsu0131/joblist.git
```

**Comment by atsu0131** [comment]
ありがとうございます！これでできました！
git remote set-url origin git@github.com:atsu0131/kintai.git
